/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL_DIRECT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "InfernoLogApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "InfernoLogUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "SENTRY_DSN": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}